### PR TITLE
Add 'try' warning

### PR DESCRIPTION
**Pull request by tbrenard**
The word 'try' is also a word we should ban from our mails. Let's DO instead !

capture d ecran 2016-01-03 a 19 44 11

### CODE REVIEW

**Comment by tami-cyrus** [comment]
This is awesome!
Can you send us the link to the Zoe B article?

-
Tami Reiss
CEO
Cyrus Innovation <http://www.cyrusinnovation.com/>
212-647-7186

Agile Reinforcement to accelerate your development

Dedicated to respect and diversity


@tamireiss / @cyrusinnovation

Learn about the difference between the Cyrus way
<http://www.cyrusinnovation.com/differences-between-xp-vs-scrum-agile/> and
other consultancies.

**Comment by tbrenard** [comment]
Thanks!

Here it is: http://www.lifehack.org/articles/communication/7-things-not-to-say-and-7-things-to-start-saying.html

I've put it in the README with the other links.

**Comment by tami-cyrus** [comment]
Great! We wrote Zoe to get her research (beyond the all knowing Yoda) of
why "try" is such a big problem.

-
Tami Reiss
CEO
Cyrus Innovation <http://www.cyrusinnovation.com/>
212-647-7186

Agile Reinforcement to accelerate your development

Dedicated to respect and diversity


@tamireiss / @cyrusinnovation

Learn about the difference between the Cyrus way
<http://www.cyrusinnovation.com/differences-between-xp-vs-scrum-agile/> and
other consultancies.

**Comment by verdammelt** [comment]
Going to merge this in after a small change to the message. (Shortening it to just the Yoda quote).

**Pull request merged**
